name:                CodingDojo
version:             0.1.0.0
github:              "thma/CodingDojo"
license:             BSD3
author:              "Thomas Mahler"
maintainer:          "thma@apache.org"
copyright:           "2020 Thomas Mahler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thma/CodingDojo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  CodingDojo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CodingDojo

tests:
  CodingDojo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CodingDojo
    - hspec
    - QuickCheck
